### ISSUE TITLE
Not an issue, I just want to say thank you !!

### ISSUE THREAD

**Issue by kcvinker** [AndrejMitrovic/DWinProgramming#12]
Hi, 
The code in line 83 on "Samples/Chap17/FontRot/EZFont.d" saved me. I was struck when I tried to write the CreateFontIndirectW function. lfFaceName was the problem.

**Comment by AndrejMitrovic** [comment]
Hi,

Nice to see this is still useful to people.

But there's something I've noticed:

https://github.com/AndrejMitrovic/DWinProgramming/blob/8528cc7984444f992182a20024191c879e1dede5/Samples/Chap17/EZTest/EZFont.d#L80-L83

I think the `lf.lfFaceName[] = ' ';` can probably be removed, it's probably a mistake here. Maybe I didn't understand it was a null-terminated string at the time.

This static char array is now null-terminated by default in https://github.com/dlang/dmd/blob/35abfc4a9fdb74c3d2a6b2698728e827ae981293/druntime/src/core/sys/windows/wingdi.d#L2347

**Comment by kcvinker** [comment]
Hi, 
Yup, I see that in declaration. But your code worked like a charm. It compiled successfully.
